rows_per_frame: 543

seed: 42
test_size: 0.2
lr: 0.0001
batch_size: 128
img_size: [1, 543, 3]
epochs: 1000
patience: 100
model_path: "gru_model.pth"
load_model_path: "models/gru_model.pth"
project: "kaggle-asl-signs"
experiment_name: "gru_baseline"
model_name: "gru"
