PREPROCESS_DATA: False
TRAIN_MODEL: False
N_ROWS: 543
N_COLS: 92
N_DIMS: 3
DIM_NAMES: ['x', 'y', 'z']
SEED: 42
NUM_CLASSES: 250
IS_INTERACTIVE: True
VERBOSE: 2
INPUT_SIZE: 32
BATCH_ALL_SIGNS_N: 4
BATCH_SIZE: 256
N_EPOCHS: 50
LR_MAX: 1e-3
N_WARMUP_EPOCHS: 0
WD_RATIO: 0.05
MASK_VAL: 4237

LIPS_IDXS0: np.array([
        61, 185, 40, 39, 37, 0, 267, 269, 270, 409,
        291, 146, 91, 181, 84, 17, 314, 405, 321, 375,
        78, 191, 80, 81, 82, 13, 312, 311, 310, 415,
        95, 88, 178, 87, 14, 317, 402, 318, 324, 308,
    ])
LEFT_HAND_IDXS0: [np.arange(468,489)
RIGHT_HAND_IDXS0: np.arange(522,543)
POSE_IDXS0       = np.arange(502, 512)
LANDMARK_IDXS0   = np.concatenate((LIPS_IDXS0, LEFT_HAND_IDXS0, RIGHT_HAND_IDXS0, POSE_IDXS0))
HAND_IDXS0       = np.concatenate((LEFT_HAND_IDXS0, RIGHT_HAND_IDXS0), axis=0)
N_COLS           = LANDMARK_IDXS0.size
N_COLS, LANDMARK_IDXS0


# Epsilon value for layer normalisation
LAYER_NORM_EPS: 1e-6

# Dense layer units for landmarks
LIPS_UNITS: 384
HANDS_UNITS: 384
POSE_UNITS: 384
# final embedding and transformer embedding size
UNITS: 384

# Transformer
NUM_BLOCKS: 2
MLP_RATIO: 2

# Dropout
EMBEDDING_DROPOUT: 0.00
MLP_DROPOUT_RATIO: 0.30
CLASSIFIER_DROPOUT_RATIO: 0.10

# Initiailizers
INIT_HE_UNIFORM: tf.keras.initializers.he_uniform
INIT_GLOROT_UNIFORM: tf.keras.initializers.glorot_uniform
INIT_ZEROS: tf.keras.initializers.constant(0.0)
# Activations
GELU: tf.keras.activations.gelu
