N_ROWS: 543
N_COLS: 66  # number of landmark 
N_DIMS: 3
NUM_FRAMES: 15
SEGMENTS: 3
DIM_NAMES: ['x', 'y', 'z']
SEED: 42
NUM_CLASSES: 250
IS_INTERACTIVE: True
VERBOSE: 2
INPUT_SIZE: 64
BATCH_ALL_SIGNS_N: 4
BATCH_SIZE: 1024
N_EPOCHS: 1000
LR_MAX: 1.e-3
N_WARMUP_EPOCHS: 0
WD_RATIO: 0.05
MASK_VAL: 4237


# Epsilon value for layer normalisation
LAYER_NORM_EPS: 1.e-6

# Dense layer units for landmarks
LIPS_UNITS: 384
HANDS_UNITS: 384
POSE_UNITS: 384

# FC
UNITS: 512
# Base 5 best  8 3 best
NUM_BLOCKS: 2
DROPRATE: 0.30
MLP_DROPOUT_RATE: 0.10
MLP_UNITS: 384

RESIDUAL_UNITS: 512
RESIDUAL_DROPRATE: 0.25

# Transformer
# NUM_BLOCKS: 4
MLP_RATIO: 2

# Dropout
EMBEDDING_DROPOUT: 0.00
MLP_DROPOUT_RATIO: 0.30
CLASSIFIER_DROPOUT_RATIO: 0.10

# Optimizer
lr: 1.e-5
weight_decay: 1.e-5  # original 1.e-5
clipnorm: 1.0

# Kfold
CREATE_KFOLD: True
k: 7

# Earlystopping
PATIENCE: 400

# Path
TRAIN_CSV_PATH: "input/train.csv"
MODEL_PATH: "models/fc_3layers.h5"
MODEL_WEIGHTS_PATH: "models/fc_3layers"

# Wandb
PROJECT: "kaggle-asl-signs"
EXPERIMENT_NAME: "100%_fc_3layers"
MODEL_NAME: "fc"

